[Android_VeryHigh DeviceProfile]
CVars=r.MobileContentScaleFactor=1.25
CVars=r.Mobile.DeviceEvaluation=3
CVars=r.Vulkan.RobustBufferAccess=1
CVars=r.Android.DisableVulkanSupport=0
CVars=r.SecondaryScreenPercentage.GameViewport=125
CVars=r.imp.SSMbScaleLod0=0.5
CVars=r.imp.SSMbScaleLod1=1.5
CVars=sg.ViewDistanceQuality=3
CVars=sg.AntiAliasingQuality=3
CVars=sg.ShadowQuality=3
CVars=sg.PostProcessQuality=4
CVars=sg.TextureQuality=3
CVars=sg.FoliageQuality=3
CVars=sg.ShadingQuality=3
CVars=wp.Runtime.LoadingRangeScale=1.25
CVars=wp.Runtime.PlannedLoadingRangeScale=1.15
CVars=r.AFME.Enable=1
CVars=r.AFMEIsProcessTransparent=1
CVars=r.AFMEIsTransparentReliable=1

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
a.UseSwappyForFramePacing=1
bEnableDynamicMaxFPS=False
bSupportsVulkan=True
bSupportsVulkanSM5=True
FrameRateLock=120
r.SetFramePace=120
r.VSync=0
rhi.SyncInterval=1

[Android_TegraK1 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno8xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno810 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno820 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno825 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno830 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno840 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno850 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno4xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno4xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno5xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno5xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno660 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno6xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno6xx_Lowest DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno6xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno6xx_Mid DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno6xx_High DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno730 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno735 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno740 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno750 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3
CVars=r.MobileContentScaleFactor=1.0
CVars=r.SecondaryScreenPercentage.GameViewport=100
; Unlock Ray Tracing
CVars=r.RayTracing=1
CVars=sg.RayTracingQuality=1
CVars=r.Android.AllowRayTracing=1
CVars=r.Vulkan.RayTracing=1
; Ray Tracing
CVars=r.RayTracing.Shadows.SamplesPerPixel=1
CVars=r.RayTracing.Reflections.MaxBounces=1
CVars=r.RayTracing.Reflections.Shadows=1
CVars=r.RayTracing.Reflections.SamplesPerPixel=1
CVars=r.RayTracing.Reflections.Translucency=1
; Global Illumination
CVars=r.RayTracing.GlobalIllumination=1
CVars=r.RayTracing.GlobalIllumination.MaxBounces=1
CVars=r.SSGI.Enable=1
CVars=r.SSGI.Quality=3
; Kualitas Cinematic
CVars=sg.ViewDistanceQuality=4
CVars=sg.ShadowQuality=4
CVars=sg.AntiAliasingQuality=4
CVars=sg.PostProcessQuality=4
CVars=sg.TextureQuality=4
CVars=sg.EffectsQuality=4
CVars=sg.FoliageQuality=4
CVars=sg.ShadingQuality=4

[Android_Adreno7xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno7xx_Lowest DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno7xx_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno7xx_Mid DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Adreno7xx_High DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Xclipse950 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Xclipse940 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Xclipse930 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Xclipse5xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_T6xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_T7xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_T8xx DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G5x DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G71 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G72 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G76 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G77 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G78 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G5x_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G61x DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G62x DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G68 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G710 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G715 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G720 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G925 DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_G92x DeviceProfile]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

[Android_Mali_Gx_Ultra]
BaseProfileName=Android_VeryHigh
CVars=r.Mobile.DeviceEvaluation=3

